services:
  app:
    build: .
    container_name: judge-api
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/my_oj

  db:
    image: postgres:16
    container_name: my-oj-postgres
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: my_oj
    ports:
      - "5433:5432"
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/init.sql